[package]
name = "mdref"
version = "0.1.0"
edition = "2024"
authors = ["Student Wei <studentweis@gmail.com>"]
repository = "https://github.com/studentweis/mdref"


[dependencies]
clap = { version = "4.0", features = ["derive"] }
walkdir = "2.3"
regex = "1.5"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
