[package]
name = "mdref"
version = "0.1.1"
edition = "2024"
authors = ["Student Wei <studentweis@gmail.com>"]
repository = "https://github.com/studentweis/mdref"
description = "A tool to find and manage Markdown file link references."
readme = "README.md"
license = "MIT"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
walkdir = "2.3"
regex = "1.5"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
